"""
Iteration 94 - Test Solomon AI Deliverable Generation (PDF/PPTX/DOCX/XLSX) and Custom Report Builder
Tests for:
1. PDF generation via /api/solomon/generate-deliverable
2. PPTX generation via /api/solomon/generate-deliverable
3. DOCX generation via /api/solomon/generate-deliverable
4. XLSX generation via /api/solomon/generate-deliverable
5. Deliverables with table_data parameter
6. Deliverables with sections parameter
7. Custom Report Preview via /api/admin/reports/custom/preview
8. Custom Report Export CSV via /api/admin/reports/custom/export
9. Custom Report Save via /api/admin/reports/custom
10. Custom Report List via /api/admin/reports/custom
"""

import pytest
import requests
import os

BASE_URL = os.environ.get('REACT_APP_BACKEND_URL', '').rstrip('/')

# Test credentials
PLATFORM_ADMIN_EMAIL = "admin@solomonai.us"
PLATFORM_ADMIN_PASSWORD = os.environ.get("TEST_PASSWORD", "Demo2026!")
CHURCH_ADMIN_EMAIL = "shannonnieman1030@gmail.com"
CHURCH_ADMIN_PASSWORD = os.environ.get("TEST_PASSWORD", "Demo2026!")


class TestAuthentication:
    """Helper class for authentication"""
    
    @staticmethod
    def get_platform_admin_token():
        """Get platform admin session token"""
        response = requests.post(f"{BASE_URL}/api/auth/login", json={
            "email": PLATFORM_ADMIN_EMAIL,
            "password": PLATFORM_ADMIN_PASSWORD
        })
        if response.status_code == 200:
            data = response.json()
            return data.get("session_token") or data.get("token")
        return None
    
    @staticmethod
    def get_church_admin_token():
        """Get church admin session token"""
        response = requests.post(f"{BASE_URL}/api/auth/login", json={
            "email": CHURCH_ADMIN_EMAIL,
            "password": CHURCH_ADMIN_PASSWORD
        })
        if response.status_code == 200:
            data = response.json()
            return data.get("session_token") or data.get("token")
        return None


class TestDeliverableGeneration:
    """Test Solomon AI deliverable generation (PDF/PPTX/DOCX/XLSX)"""
    
    @pytest.fixture(autouse=True)
    def setup(self):
        """Setup authentication for deliverable tests"""
        self.token = TestAuthentication.get_platform_admin_token()
        if not self.token:
            # Try church admin as fallback
            self.token = TestAuthentication.get_church_admin_token()
        self.headers = {
            "Authorization": f"Bearer {self.token}",
            "Content-Type": "application/json"
        } if self.token else {"Content-Type": "application/json"}
    
    def test_pdf_generation_basic(self):
        """Test PDF generation with basic content"""
        response = requests.post(f"{BASE_URL}/api/solomon/generate-deliverable", 
            headers=self.headers,
            json={
                "type": "pdf",
                "title": "Test PDF Report",
                "content": "This is a test PDF document generated by Solomon AI.\n\nIt contains multiple paragraphs."
            }
        )
        assert response.status_code == 200, f"Expected 200, got {response.status_code}: {response.text}"
        assert "application/pdf" in response.headers.get("content-type", ""), "Expected PDF content type"
        assert len(response.content) > 1000, f"PDF should be >1KB, got {len(response.content)} bytes"
        print(f"✓ PDF generated: {len(response.content)} bytes")
    
    def test_pptx_generation_basic(self):
        """Test PPTX generation with basic content"""
        response = requests.post(f"{BASE_URL}/api/solomon/generate-deliverable",
            headers=self.headers,
            json={
                "type": "pptx",
                "title": "Test PowerPoint Presentation",
                "content": "This is slide content for the presentation."
            }
        )
        assert response.status_code == 200, f"Expected 200, got {response.status_code}: {response.text}"
        content_type = response.headers.get("content-type", "")
        assert "presentationml" in content_type or "application/vnd" in content_type, f"Expected PPTX content type, got {content_type}"
        assert len(response.content) > 20000, f"PPTX should be >20KB, got {len(response.content)} bytes"
        print(f"✓ PPTX generated: {len(response.content)} bytes")
    
    def test_docx_generation_basic(self):
        """Test DOCX generation with basic content"""
        response = requests.post(f"{BASE_URL}/api/solomon/generate-deliverable",
            headers=self.headers,
            json={
                "type": "docx",
                "title": "Test Word Document",
                "content": "This is a test Word document.\n\nIt has multiple paragraphs of content."
            }
        )
        assert response.status_code == 200, f"Expected 200, got {response.status_code}: {response.text}"
        content_type = response.headers.get("content-type", "")
        assert "wordprocessingml" in content_type or "application/vnd" in content_type, f"Expected DOCX content type, got {content_type}"
        assert len(response.content) > 5000, f"DOCX should be >5KB, got {len(response.content)} bytes"
        print(f"✓ DOCX generated: {len(response.content)} bytes")
    
    def test_xlsx_generation_basic(self):
        """Test XLSX generation with basic content"""
        response = requests.post(f"{BASE_URL}/api/solomon/generate-deliverable",
            headers=self.headers,
            json={
                "type": "xlsx",
                "title": "Test Excel Spreadsheet",
                "content": "Row 1 data\nRow 2 data\nRow 3 data"
            }
        )
        assert response.status_code == 200, f"Expected 200, got {response.status_code}: {response.text}"
        content_type = response.headers.get("content-type", "")
        assert "spreadsheetml" in content_type or "application/vnd" in content_type, f"Expected XLSX content type, got {content_type}"
        assert len(response.content) > 3000, f"XLSX should be >3KB, got {len(response.content)} bytes"
        print(f"✓ XLSX generated: {len(response.content)} bytes")
    
    def test_pdf_with_table_data(self):
        """Test PDF generation with table_data parameter"""
        response = requests.post(f"{BASE_URL}/api/solomon/generate-deliverable",
            headers=self.headers,
            json={
                "type": "pdf",
                "title": "Report with Table",
                "content": "This report includes tabular data below.",
                "table_data": {
                    "headers": ["Name", "Amount", "Date"],
                    "rows": [
                        ["John Doe", "$100.00", "2026-01-15"],
                        ["Jane Smith", "$250.00", "2026-01-16"],
                        ["Bob Wilson", "$75.00", "2026-01-17"]
                    ]
                }
            }
        )
        assert response.status_code == 200, f"Expected 200, got {response.status_code}: {response.text}"
        assert "application/pdf" in response.headers.get("content-type", "")
        # PDF with table should be larger
        assert len(response.content) > 2000, f"PDF with table should be >2KB, got {len(response.content)} bytes"
        print(f"✓ PDF with table generated: {len(response.content)} bytes")
    
    def test_docx_with_table_data(self):
        """Test DOCX generation with table_data parameter"""
        response = requests.post(f"{BASE_URL}/api/solomon/generate-deliverable",
            headers=self.headers,
            json={
                "type": "docx",
                "title": "Word Document with Table",
                "content": "This document includes a data table.",
                "table_data": {
                    "headers": ["Member", "Status", "Joined"],
                    "rows": [
                        ["Alice Brown", "Active", "2025-06-01"],
                        ["Charlie Davis", "Inactive", "2024-12-15"]
                    ]
                }
            }
        )
        assert response.status_code == 200, f"Expected 200, got {response.status_code}: {response.text}"
        content_type = response.headers.get("content-type", "")
        assert "wordprocessingml" in content_type or "application/vnd" in content_type
        print(f"✓ DOCX with table generated: {len(response.content)} bytes")
    
    def test_xlsx_with_table_data(self):
        """Test XLSX generation with table_data parameter"""
        response = requests.post(f"{BASE_URL}/api/solomon/generate-deliverable",
            headers=self.headers,
            json={
                "type": "xlsx",
                "title": "Excel with Data",
                "content": "",
                "table_data": {
                    "headers": ["Fund", "Total", "Count"],
                    "rows": [
                        ["General", "$5000", "50"],
                        ["Building", "$2500", "25"],
                        ["Missions", "$1500", "15"]
                    ]
                }
            }
        )
        assert response.status_code == 200, f"Expected 200, got {response.status_code}: {response.text}"
        content_type = response.headers.get("content-type", "")
        assert "spreadsheetml" in content_type or "application/vnd" in content_type
        print(f"✓ XLSX with table generated: {len(response.content)} bytes")
    
    def test_pptx_with_sections(self):
        """Test PPTX generation with sections parameter (creates multiple slides)"""
        response = requests.post(f"{BASE_URL}/api/solomon/generate-deliverable",
            headers=self.headers,
            json={
                "type": "pptx",
                "title": "Multi-Slide Presentation",
                "content": "Introduction slide content",
                "sections": [
                    {"heading": "Section 1: Overview", "body": "This is the overview section with key points."},
                    {"heading": "Section 2: Details", "body": "Detailed information goes here.\nMultiple lines supported."},
                    {"heading": "Section 3: Conclusion", "body": "Summary and next steps."}
                ]
            }
        )
        assert response.status_code == 200, f"Expected 200, got {response.status_code}: {response.text}"
        content_type = response.headers.get("content-type", "")
        assert "presentationml" in content_type or "application/vnd" in content_type
        # PPTX with multiple slides should be larger
        assert len(response.content) > 25000, f"PPTX with sections should be >25KB, got {len(response.content)} bytes"
        print(f"✓ PPTX with sections generated: {len(response.content)} bytes")
    
    def test_docx_with_sections(self):
        """Test DOCX generation with sections parameter"""
        response = requests.post(f"{BASE_URL}/api/solomon/generate-deliverable",
            headers=self.headers,
            json={
                "type": "docx",
                "title": "Document with Sections",
                "content": "Executive summary paragraph.",
                "sections": [
                    {"heading": "Chapter 1", "body": "Content for chapter one."},
                    {"heading": "Chapter 2", "body": "Content for chapter two."}
                ]
            }
        )
        assert response.status_code == 200, f"Expected 200, got {response.status_code}: {response.text}"
        content_type = response.headers.get("content-type", "")
        assert "wordprocessingml" in content_type or "application/vnd" in content_type
        print(f"✓ DOCX with sections generated: {len(response.content)} bytes")


class TestCustomReportBuilder:
    """Test Custom Report Builder endpoints"""
    
    @pytest.fixture(autouse=True)
    def setup(self):
        """Setup authentication for report tests"""
        self.token = TestAuthentication.get_church_admin_token()
        if not self.token:
            self.token = TestAuthentication.get_platform_admin_token()
        self.headers = {
            "Authorization": f"Bearer {self.token}",
            "Content-Type": "application/json"
        } if self.token else {"Content-Type": "application/json"}
    
    def test_custom_report_preview_people(self):
        """Test custom report preview with people source"""
        response = requests.post(f"{BASE_URL}/api/admin/reports/custom/preview",
            headers=self.headers,
            json={
                "source": "people",
                "fields": ["first_name", "last_name", "email"],
                "filters": [],
                "limit": 10
            }
        )
        assert response.status_code == 200, f"Expected 200, got {response.status_code}: {response.text}"
        data = response.json()
        assert "columns" in data, "Response should have columns"
        assert "rows" in data, "Response should have rows"
        assert "total_count" in data, "Response should have total_count"
        assert isinstance(data["columns"], list), "Columns should be a list"
        assert isinstance(data["rows"], list), "Rows should be a list"
        print(f"✓ Custom report preview: {len(data['rows'])} rows, {data['total_count']} total")
    
    def test_custom_report_preview_donations(self):
        """Test custom report preview with donations source"""
        response = requests.post(f"{BASE_URL}/api/admin/reports/custom/preview",
            headers=self.headers,
            json={
                "source": "donations",
                "fields": ["donor_name", "amount", "donation_date"],
                "filters": [],
                "limit": 10
            }
        )
        assert response.status_code == 200, f"Expected 200, got {response.status_code}: {response.text}"
        data = response.json()
        assert "columns" in data
        assert "rows" in data
        print(f"✓ Donations report preview: {len(data['rows'])} rows")
    
    def test_custom_report_preview_with_filter(self):
        """Test custom report preview with filter"""
        response = requests.post(f"{BASE_URL}/api/admin/reports/custom/preview",
            headers=self.headers,
            json={
                "source": "people",
                "fields": ["first_name", "last_name", "membership_status"],
                "filters": [{"field": "membership_status", "op": "=", "value": "active"}],
                "limit": 20
            }
        )
        assert response.status_code == 200, f"Expected 200, got {response.status_code}: {response.text}"
        data = response.json()
        assert "columns" in data
        print(f"✓ Filtered report preview: {len(data['rows'])} rows")
    
    def test_custom_report_preview_invalid_source(self):
        """Test custom report preview with invalid source returns 400"""
        response = requests.post(f"{BASE_URL}/api/admin/reports/custom/preview",
            headers=self.headers,
            json={
                "source": "invalid_source",
                "fields": ["field1"],
                "filters": []
            }
        )
        assert response.status_code == 400, f"Expected 400 for invalid source, got {response.status_code}"
        print("✓ Invalid source correctly rejected")
    
    def test_custom_report_export_csv(self):
        """Test custom report CSV export"""
        response = requests.post(f"{BASE_URL}/api/admin/reports/custom/export",
            headers=self.headers,
            json={
                "source": "people",
                "fields": ["first_name", "last_name", "email"]
            }
        )
        assert response.status_code == 200, f"Expected 200, got {response.status_code}: {response.text}"
        content_type = response.headers.get("content-type", "")
        assert "text/csv" in content_type, f"Expected CSV content type, got {content_type}"
        # Check CSV has content
        csv_content = response.text
        assert "first_name" in csv_content or "last_name" in csv_content, "CSV should contain field headers"
        print(f"✓ CSV export: {len(csv_content)} chars")
    
    def test_custom_report_save(self):
        """Test saving a custom report configuration"""
        import uuid
        report_name = f"TEST_Report_{uuid.uuid4().hex[:8]}"
        response = requests.post(f"{BASE_URL}/api/admin/reports/custom",
            headers=self.headers,
            json={
                "name": report_name,
                "source": "people",
                "fields": ["first_name", "last_name", "email", "membership_status"],
                "filters": [],
                "group_by": "",
                "aggregation": "count"
            }
        )
        assert response.status_code == 200, f"Expected 200, got {response.status_code}: {response.text}"
        data = response.json()
        assert "report" in data or "message" in data, "Response should confirm save"
        if "report" in data:
            assert data["report"].get("name") == report_name, "Saved report name should match"
            assert "id" in data["report"], "Saved report should have an ID"
        print(f"✓ Report saved: {report_name}")
        return report_name
    
    def test_custom_report_list(self):
        """Test listing saved custom reports"""
        response = requests.get(f"{BASE_URL}/api/admin/reports/custom",
            headers=self.headers
        )
        assert response.status_code == 200, f"Expected 200, got {response.status_code}: {response.text}"
        data = response.json()
        assert "reports" in data, "Response should have reports array"
        assert isinstance(data["reports"], list), "Reports should be a list"
        print(f"✓ Report list: {len(data['reports'])} saved reports")


class TestLandingPageHeroSection:
    """Test that landing page hero does NOT show God Mode KPI screenshot"""
    
    def test_landing_page_loads(self):
        """Test landing page is accessible"""
        response = requests.get(f"{BASE_URL}/")
        # Landing page should load (may redirect or return HTML)
        assert response.status_code in [200, 301, 302], f"Landing page should be accessible, got {response.status_code}"
        print("✓ Landing page accessible")


if __name__ == "__main__":
    pytest.main([__file__, "-v", "--tb=short"])
